package gregtech.api.enums;

import gregtech.api.interfaces.IIconContainer;

public final class TextureSet {
    public static final TextureSet
            SET_NONE = new TextureSet("NONE"), SET_DULL = new TextureSet("DULL"), SET_RUBY = new TextureSet("RUBY"), SET_OPAL = new TextureSet("OPAL"), SET_LEAF = new TextureSet("LEAF"), SET_WOOD = new TextureSet("WOOD"), SET_SAND = new TextureSet("SAND"), SET_FINE = new TextureSet("FINE"), SET_FIERY = new TextureSet("FIERY"), SET_FLUID = new TextureSet("FLUID"), SET_ROUGH = new TextureSet("ROUGH"), SET_PAPER = new TextureSet("PAPER"), SET_GLASS = new TextureSet("GLASS"), SET_FLINT = new TextureSet("FLINT"), SET_LAPIS = new TextureSet("LAPIS"), SET_SHINY = new TextureSet("SHINY"), SET_SHARDS = new TextureSet("SHARDS"), SET_POWDER = new TextureSet("POWDER"), SET_QUARTZ = new TextureSet("QUARTZ"), SET_EMERALD = new TextureSet("EMERALD"), SET_DIAMOND = new TextureSet("DIAMOND"), SET_LIGNITE = new TextureSet("LIGNITE"), SET_MAGNETIC = new TextureSet("MAGNETIC"), SET_METALLIC = new TextureSet("METALLIC"), SET_NETHERSTAR = new TextureSet("NETHERSTAR"), SET_GEM_VERTICAL = new TextureSet("GEM_VERTICAL"), SET_GEM_HORIZONTAL = new TextureSet("GEM_HORIZONTAL");

    /**
     * For the Indices of OrePrefixes you need to look into the OrePrefix Enum.
     */
    public static final short
            INDEX_wire = 69, INDEX_foil = 70, INDEX_block1 = 71, INDEX_block2 = 72, INDEX_block3 = 73, INDEX_block4 = 74, INDEX_block5 = 75, INDEX_block6 = 76;

    public final IIconContainer[] mTextures = new IIconContainer[128];
    public final String mSetName;
    private final static String text1 = "materialicons/";
    private final static String text2 = "/void";

    public TextureSet(String aSetName) {
        mSetName = aSetName;
        mTextures[0] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/dustTiny");
        mTextures[1] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/dustSmall");
        mTextures[2] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/dust");
        mTextures[3] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/dustImpure");
        mTextures[4] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/dustPure");
        mTextures[5] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crushed");
        mTextures[6] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crushedPurified");
        mTextures[7] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crushedCentrifuged");
        mTextures[8] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gem");
        mTextures[9] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/nugget");
        mTextures[10] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[11] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ingot");
        mTextures[12] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ingotHot");
        mTextures[13] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ingotDouble");
        mTextures[14] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ingotTriple");
        mTextures[15] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ingotQuadruple");
        mTextures[16] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ingotQuintuple");
        mTextures[17] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/plate");
        mTextures[18] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/plateDouble");
        mTextures[19] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/plateTriple");
        mTextures[20] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/plateQuadruple");
        mTextures[21] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/plateQuintuple");
        mTextures[22] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/plateDense");
        mTextures[23] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/stick");
        mTextures[24] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/lens");
        mTextures[25] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/round");
        mTextures[26] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/bolt");
        mTextures[27] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/screw");
        mTextures[28] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/ring");
        mTextures[29] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/foil");
        mTextures[30] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/cell");
        mTextures[31] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/cellPlasma");
        mTextures[32] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadSword");
        mTextures[33] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadPickaxe");
        mTextures[34] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadShovel");
        mTextures[35] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadAxe");
        mTextures[36] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadHoe");
        mTextures[37] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadHammer");
        mTextures[38] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadFile");
        mTextures[39] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadSaw");
        mTextures[40] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadDrill");
        mTextures[41] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadChainsaw");
        mTextures[42] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadWrench");
        mTextures[43] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadUniversalSpade");
        mTextures[44] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadSense");
        mTextures[45] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadPlow");
        mTextures[46] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadArrow");
        mTextures[47] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadScrewdriver");
        mTextures[48] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadBuzzSaw");
        mTextures[49] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/toolHeadSoldering");
        mTextures[50] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[51] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/wireFine");
        mTextures[52] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gearGtSmall");
        mTextures[53] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/rotor");
        mTextures[54] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/stickLong");
        mTextures[55] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/springSmall");
        mTextures[56] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/spring");
        mTextures[57] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/arrowGtWood");
        mTextures[58] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/arrowGtPlastic");
        mTextures[59] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gemChipped");
        mTextures[60] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gemFlawed");
        mTextures[61] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gemFlawless");
        mTextures[62] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gemExquisite");
        mTextures[63] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/gearGt");
        mTextures[64] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[65] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[66] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[67] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/oreSmall");
        mTextures[68] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/ore");
        mTextures[69] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/wire");
        mTextures[70] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/foil");
        mTextures[71] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/block1");
        mTextures[72] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/block2");
        mTextures[73] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/block3");
        mTextures[74] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/block4");
        mTextures[75] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/block5");
        mTextures[76] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/block6");
        mTextures[77] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/pipeSide");
        mTextures[78] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/pipeTiny");
        mTextures[79] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/pipeSmall");
        mTextures[80] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/pipeMedium");
        mTextures[81] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/pipeLarge");
        mTextures[82] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/pipeHuge");
        mTextures[83] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + "/frameGt");
        mTextures[84] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[85] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[86] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[87] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[88] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[89] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[90] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[91] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[92] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[93] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[94] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[95] = new Textures.BlockIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[96] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crateGtDust");
        mTextures[97] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crateGtIngot");
        mTextures[98] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crateGtGem");
        mTextures[99] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/crateGtPlate");
        mTextures[100] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + "/turbineBlade");
        mTextures[101] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[102] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[103] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[104] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[105] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[106] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[107] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[108] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[109] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[110] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[111] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[112] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[113] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[114] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[115] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[116] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[117] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[118] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[119] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[120] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[121] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[122] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[123] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[124] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[125] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[126] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
        mTextures[127] = new Textures.ItemIcons.CustomIcon(text1 + mSetName + text2);
    }
}